// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5s_1zWHSmM7Z_iXMe8fpvYbrQzIsiU48',
    appId: '1:837036266089:web:a6b27889d0e973165d08f8',
    messagingSenderId: '837036266089',
    projectId: 'project-2048-94448',
    authDomain: 'project-2048-94448.firebaseapp.com',
    storageBucket: 'project-2048-94448.appspot.com',
    measurementId: 'G-NJ7ZJ0GT08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu33WuLT-NGV5CMtiGhFM97TOxC_gmPUU',
    appId: '1:837036266089:android:6ef228bdc1d89e345d08f8',
    messagingSenderId: '837036266089',
    projectId: 'project-2048-94448',
    storageBucket: 'project-2048-94448.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgcgF2SY4a6TYYWnyBil1lnNi-4zHSerM',
    appId: '1:837036266089:ios:151e7a3cba2c15a65d08f8',
    messagingSenderId: '837036266089',
    projectId: 'project-2048-94448',
    storageBucket: 'project-2048-94448.appspot.com',
    iosClientId: '837036266089-0ulab6lvucrserjaml0smjsfkidcm6ja.apps.googleusercontent.com',
    iosBundleId: 'com.example.lalalala',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgcgF2SY4a6TYYWnyBil1lnNi-4zHSerM',
    appId: '1:837036266089:ios:151e7a3cba2c15a65d08f8',
    messagingSenderId: '837036266089',
    projectId: 'project-2048-94448',
    storageBucket: 'project-2048-94448.appspot.com',
    iosClientId: '837036266089-0ulab6lvucrserjaml0smjsfkidcm6ja.apps.googleusercontent.com',
    iosBundleId: 'com.example.lalalala',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5s_1zWHSmM7Z_iXMe8fpvYbrQzIsiU48',
    appId: '1:837036266089:web:481f9bce02f102905d08f8',
    messagingSenderId: '837036266089',
    projectId: 'project-2048-94448',
    authDomain: 'project-2048-94448.firebaseapp.com',
    storageBucket: 'project-2048-94448.appspot.com',
    measurementId: 'G-FMPXZ0M72E',
  );
}
